config/routes.rb
Rails.application.routes.draw do
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#homepage"
  get 'team', to: 'static_pages#team'
  get 'contact', to:'static_pages#contact'
  get 'cgv', to:'static_pages#cgv'
  get 'faq', to:'static_pages#faq'
  get 'jobs', to:'static_pages#jobs'

  devise_for :customers

  resource :cart, only: [:show, :create, :destroy] do
    resources :cart_contents, only: [:show, :new, :create, :destroy]
  end


  resource :customer do
    resources :orders
  end
  resources :foodtrucks do
    resources :votes, only: [:show, :create]
    resources :items do
    end
  end

  namespace :myfoodtruck do
    root 'dashboards#show'
    devise_for :foodtrucks
    resource :dashboard, only: [:show]
    resource :foodtruck, only: [:show, :edit, :update, :destroy] do
      resources :items
      resources :orders, only: [:index, :show, :update, :edit]
    end
  end

end

app/models/foodtruck.rb
class Foodtruck < ApplicationRecord
  after_create :welcome_send

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items
  has_many :orders
  has_one_attached :pictures
  has_one_attached :logo
  has_one :location
  has_many :votes

  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/ }
  validates :password, presence: true, length: { in: 6..20 }, on: :create

  def welcome_send
    FoodtruckMailer.welcome_email(self).deliver_now
  end

  def number_of_votes_last_24h
    Vote.last_24h.where(foodtruck: self).count
  end

  def locations_most_voted
    votes = Vote.last_24h.where(foodtruck: self)
    votes = votes.map do |vote|
      if vote.customer != nil
        vote = vote.customer.location_id
      end
    end

    #Removing the nil values that may arise from a deleted customer profile
    freq = votes.inject(Hash.new(0)) { |k,v| k[v] += 1; k }.delete_if { |k, v| k.nil? || v.nil? }

    #Sorting the hashes by values, the locations with the most votes first, and then convert the hashes into an array
    freq = freq.sort_by{|k, v| -v}.flatten
  end

  def total_price_orders_current_day
    if self.orders.where("updated_at > ?", Date.today).any?
      orders_of_the_day = self.orders.where("updated_at > ?", Date.today)  
      orders_of_the_day.map{|order| order.total_price}.reduce(:+)
    else
      return 0
    end
  end

  def total_price_orders_current_month
    if self.orders.where("updated_at > ?", Date.today.at_beginning_of_month).any?
      orders_of_the_month = self.orders.where("updated_at > ?", Date.today.at_beginning_of_month)  
      orders_of_the_month.map{|order| order.total_price}.reduce(:+)
    else
      return 0
    end
  end

end

app/controllers/feedtruck/foodtrucks_controller.rb
class Feedtruck::FoodtrucksController < ApplicationController
  before_action :set_foodtruck_foodtruck, only: %i[ show edit update destroy ]

  # GET /foodtruck/foodtrucks or /foodtruck/foodtrucks.json
  def index
    @foodtruck_foodtrucks = Foodtruck::Foodtruck.all
  end

  # GET /foodtruck/foodtrucks/1 or /foodtruck/foodtrucks/1.json
  def show
  end

  # GET /foodtruck/foodtrucks/new
  def new
    @foodtruck_foodtruck = Foodtruck::Foodtruck.new
  end

  # GET /foodtruck/foodtrucks/1/edit
  def edit
  end

  # POST /foodtruck/foodtrucks or /foodtruck/foodtrucks.json
  def create
    @foodtruck_foodtruck = Foodtruck::Foodtruck.new(foodtruck_foodtruck_params)

    respond_to do |format|
      if @foodtruck_foodtruck.save
        format.html { redirect_to @foodtruck_foodtruck, notice: "Foodtruck was successfully created." }
        format.json { render :show, status: :created, location: @foodtruck_foodtruck }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @foodtruck_foodtruck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foodtruck/foodtrucks/1 or /foodtruck/foodtrucks/1.json
  def update
    respond_to do |format|
      if @foodtruck_foodtruck.update(foodtruck_foodtruck_params)
        format.html { redirect_to @foodtruck_foodtruck, notice: "Foodtruck was successfully updated." }
        format.json { render :show, status: :ok, location: @foodtruck_foodtruck }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @foodtruck_foodtruck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foodtruck/foodtrucks/1 or /foodtruck/foodtrucks/1.json
  def destroy
    @foodtruck_foodtruck.destroy
    respond_to do |format|
      format.html { redirect_to foodtruck_foodtrucks_url, notice: "Foodtruck was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foodtruck_foodtruck
      @foodtruck_foodtruck = Foodtruck::Foodtruck.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def foodtruck_foodtruck_params
      params.fetch(:foodtruck_foodtruck, {})
    end
end

app/controllers/foodtruck/dashboards_controller.rb
class Foodtruck::DashboardsController < ApplicationController
  before_action :set_foodtruck_dashboard, only: %i[ show edit update destroy ]

  # GET /foodtruck/dashboards or /foodtruck/dashboards.json
  def index
    @foodtruck_dashboards = Foodtruck::Dashboard.all
  end

  # GET /foodtruck/dashboards/1 or /foodtruck/dashboards/1.json
  def show
  end

  # GET /foodtruck/dashboards/new
  def new
    @foodtruck_dashboard = Foodtruck::Dashboard.new
  end

  # GET /foodtruck/dashboards/1/edit
  def edit
  end

  # POST /foodtruck/dashboards or /foodtruck/dashboards.json
  def create
    @foodtruck_dashboard = Foodtruck::Dashboard.new(foodtruck_dashboard_params)

    respond_to do |format|
      if @foodtruck_dashboard.save
        format.html { redirect_to @foodtruck_dashboard, notice: "Dashboard was successfully created." }
        format.json { render :show, status: :created, location: @foodtruck_dashboard }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @foodtruck_dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foodtruck/dashboards/1 or /foodtruck/dashboards/1.json
  def update
    respond_to do |format|
      if @foodtruck_dashboard.update(foodtruck_dashboard_params)
        format.html { redirect_to @foodtruck_dashboard, notice: "Dashboard was successfully updated." }
        format.json { render :show, status: :ok, location: @foodtruck_dashboard }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @foodtruck_dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foodtruck/dashboards/1 or /foodtruck/dashboards/1.json
  def destroy
    @foodtruck_dashboard.destroy
    respond_to do |format|
      format.html { redirect_to foodtruck_dashboards_url, notice: "Dashboard was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foodtruck_dashboard
      @foodtruck_dashboard = Foodtruck::Dashboard.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def foodtruck_dashboard_params
      params.fetch(:foodtruck_dashboard, {})
    end
end

app/controllers/foodtruck/foodtrucks_controller.rb
class Foodtruck::FoodtrucksController < ApplicationController
  before_action :set_foodtruck_foodtruck, only: %i[ show edit update destroy ]

  # GET /foodtruck/foodtrucks or /foodtruck/foodtrucks.json
  def index
    @foodtruck_foodtrucks = Foodtruck::Foodtruck.all
  end

  # GET /foodtruck/foodtrucks/1 or /foodtruck/foodtrucks/1.json
  def show
  end

  # GET /foodtruck/foodtrucks/new
  def new
    @foodtruck_foodtruck = Foodtruck::Foodtruck.new
  end

  # GET /foodtruck/foodtrucks/1/edit
  def edit
  end

  # POST /foodtruck/foodtrucks or /foodtruck/foodtrucks.json
  def create
    @foodtruck_foodtruck = Foodtruck::Foodtruck.new(foodtruck_foodtruck_params)

    respond_to do |format|
      if @foodtruck_foodtruck.save
        format.html { redirect_to @foodtruck_foodtruck, notice: "Foodtruck was successfully created." }
        format.json { render :show, status: :created, location: @foodtruck_foodtruck }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @foodtruck_foodtruck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foodtruck/foodtrucks/1 or /foodtruck/foodtrucks/1.json
  def update
    respond_to do |format|
      if @foodtruck_foodtruck.update(foodtruck_foodtruck_params)
        format.html { redirect_to @foodtruck_foodtruck, notice: "Foodtruck was successfully updated." }
        format.json { render :show, status: :ok, location: @foodtruck_foodtruck }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @foodtruck_foodtruck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foodtruck/foodtrucks/1 or /foodtruck/foodtrucks/1.json
  def destroy
    @foodtruck_foodtruck.destroy
    respond_to do |format|
      format.html { redirect_to foodtruck_foodtrucks_url, notice: "Foodtruck was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foodtruck_foodtruck
      @foodtruck_foodtruck = Foodtruck::Foodtruck.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def foodtruck_foodtruck_params
      params.fetch(:foodtruck_foodtruck, {})
    end
end

app/controllers/foodtruck/items_controller.rb
class Foodtruck::ItemsController < ApplicationController
  before_action :set_foodtruck_item, only: %i[ show edit update destroy ]

  # GET /foodtruck/items or /foodtruck/items.json
  def index
    @foodtruck_items = Foodtruck::Item.all
  end

  # GET /foodtruck/items/1 or /foodtruck/items/1.json
  def show
  end

  # GET /foodtruck/items/new
  def new
    @foodtruck_item = Foodtruck::Item.new
  end

  # GET /foodtruck/items/1/edit
  def edit
  end

  # POST /foodtruck/items or /foodtruck/items.json
  def create
    @foodtruck_item = Foodtruck::Item.new(foodtruck_item_params)

    respond_to do |format|
      if @foodtruck_item.save
        format.html { redirect_to @foodtruck_item, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @foodtruck_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @foodtruck_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foodtruck/items/1 or /foodtruck/items/1.json
  def update
    respond_to do |format|
      if @foodtruck_item.update(foodtruck_item_params)
        format.html { redirect_to @foodtruck_item, notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @foodtruck_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @foodtruck_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foodtruck/items/1 or /foodtruck/items/1.json
  def destroy
    @foodtruck_item.destroy
    respond_to do |format|
      format.html { redirect_to foodtruck_items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foodtruck_item
      @foodtruck_item = Foodtruck::Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def foodtruck_item_params
      params.fetch(:foodtruck_item, {})
    end
end

app/controllers/foodtruck/orders_controller.rb
class Foodtruck::OrdersController < ApplicationController
  before_action :set_foodtruck_order, only: %i[ show edit update destroy ]

  # GET /foodtruck/orders or /foodtruck/orders.json
  def index
    @foodtruck_orders = Foodtruck::Order.all
  end

  # GET /foodtruck/orders/1 or /foodtruck/orders/1.json
  def show
  end

  # GET /foodtruck/orders/new
  def new
    @foodtruck_order = Foodtruck::Order.new
  end

  # GET /foodtruck/orders/1/edit
  def edit
  end

  # POST /foodtruck/orders or /foodtruck/orders.json
  def create
    @foodtruck_order = Foodtruck::Order.new(foodtruck_order_params)

    respond_to do |format|
      if @foodtruck_order.save
        format.html { redirect_to @foodtruck_order, notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @foodtruck_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @foodtruck_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foodtruck/orders/1 or /foodtruck/orders/1.json
  def update
    respond_to do |format|
      if @foodtruck_order.update(foodtruck_order_params)
        format.html { redirect_to @foodtruck_order, notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @foodtruck_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @foodtruck_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foodtruck/orders/1 or /foodtruck/orders/1.json
  def destroy
    @foodtruck_order.destroy
    respond_to do |format|
      format.html { redirect_to foodtruck_orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foodtruck_order
      @foodtruck_order = Foodtruck::Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def foodtruck_order_params
      params.fetch(:foodtruck_order, {})
    end
end

app/controllers/foodtrucks_controller.rb
class FoodtrucksController < ApplicationController
  before_action :set_foodtruck, only: %i[ show edit update destroy ]

  # GET /foodtrucks
  def index
    @foodtrucks = Foodtruck.all
  end

  # GET /foodtrucks/new
  def new
    @foodtruck = Foodtruck.new
  end

  # GET /foodtrucks/1/edit
  def edit
  end

  # POST /foodtrucks
  def create
    @foodtruck = Foodtruck.new(foodtruck_params)

    respond_to do |format|
      if @foodtruck.save
        format.html { redirect_to myfoodtruck_foodtruck_path, flash: { success: "Profil créé"} }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foodtrucks/1
  def update
    respond_to do |format|
      if @foodtruck.update(foodtruck_params)
        format.html { redirect_to myfoodtruck_foodtruck_path, flash: { success: "Profil mis à jour"} }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foodtrucks/1
  def destroy
    @foodtruck.destroy
    respond_to do |format|
      format.html { redirect_to foodtrucks_url, flash: { success: "Profil détruit"} }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foodtruck
      @foodtruck = Foodtruck.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def foodtruck_params
      params.require(:foodtruck).permit(:email, :password, :name, :description, :pictures, :location_id, :logo)
    end
    
end

app/controllers/myfoodtruck/foodtrucks_controller.rb
class Myfoodtruck::FoodtrucksController < ApplicationController
  before_action :set_foodtruck_foodtruck, only: %i[ show edit update destroy ]

  # GET /foodtruck/foodtrucks/1/edit
  def edit
    @locations = Location.all
  end

  # PATCH/PUT /foodtruck/foodtrucks/1 or /foodtruck/foodtrucks/1.json
  def update
    p myfoodtruck_foodtruck_params
    respond_to do |format|
      if @myfoodtruck_foodtruck.update(myfoodtruck_foodtruck_params)
        format.html { redirect_to @myfoodtruck_foodtruck, notice: "Foodtruck was successfully updated." }
        format.json { render :show, status: :ok, location: @myfoodtruck_foodtruck }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @myfoodtruck_foodtruck.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foodtruck_foodtruck
      @myfoodtruck_foodtruck = current_myfoodtruck_foodtruck
    end

    # Only allow a list of trusted parameters through.
    def myfoodtruck_foodtruck_params
      params.require(:myfoodtruck_foodtruck).permit(:email, :password, :description, :name, :pictures, :location_id, :logo)
    end

end

app/helpers/foodtrucks_helper.rb
module FoodtrucksHelper

  def is_foodtruck_profile_completed?(foodtruck)
    foodtruck.name? && foodtruck.description? && foodtruck.location_id? && foodtruck.pictures.attached? && foodtruck.items.count > 0 ? true : false
  end

  def is_current_foodtruck_profile_completed?
    current_myfoodtruck_foodtruck.name? && current_myfoodtruck_foodtruck.description? && current_myfoodtruck_foodtruck.location_id? && current_myfoodtruck_foodtruck.pictures.attached? && current_myfoodtruck_foodtruck.items.count > 0 ? true : false
  end

end

app/helpers/myfoodtruck/foodtrucks_helper.rb
module Myfoodtruck::FoodtrucksHelper
end

app/views/foodtrucks/_cardindex.html.erb
<div class="section">
  <div class="container grid-list-display">
    <% foodtrucks.each do |foodtruck| %>
      <% if is_foodtruck_profile_completed?(foodtruck) %>
        <%= link_to foodtruck_path(foodtruck.id) do %>
          <div class="card index-card">
            <div class="card-image foodtruck-cover">
              <% if foodtruck.pictures.attached? %>
                <%= image_tag foodtruck.pictures, alt: "Thumbnail [100%x225]", class:"footruck-picture" %>
              <% else %>
                <img src="https://images.pexels.com/photos/566566/pexels-photo-566566.jpeg?cs=srgb&dl=pexels-foodie-factor-566566.jpg&fm=jpg" alt="food-img" class="menu-item-img">
              <% end %>
            </div>       
            <div class="card-content">                    
              <div class="card-media is-flex is-align-items-center ">                        
                <div class="foodtruck-banner">
                  <% if foodtruck.logo.attached? %>
                    <%= image_tag foodtruck.logo, alt: "Thumbnail [100%x225]", class:"image is-48x48" %>
                  <% else %>
                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQu2DMlO0wSOdL36IyORHd0n1FAKfw0_S4jg&usqp=CAU" alt="Placeholder image" class="image is-48x48">
                  <% end %>
                </div>               
                <div class="foodtruck-info ml-5">
                  <p class="title is-size-5"><%= foodtruck.name %></p>
                </div>
              </div>      
            </div>                
          </div>
        <% end %> 
      <% end %>
    <% end %>             
  </div>
</div>

    

app/views/foodtrucks/_firstsection.html.erb
<div class="section">
  <div class="show-foodtruck container">

    <% if foodtruck.pictures.attached? %>
      <div class="banner-img", style="background-image: url(<%= rails_blob_url(foodtruck.pictures) %>); height: 300px;"></div>
    <% end %>

    <div class="foodtruck-infos columns box pt-5 mt-0 ml-0 mr-0">
      <div class="header column is-9 padding-header-foodtruck">
        <% if foodtruck.name !=nil && foodtruck.name != ""%>
          <p class="foodtruck-name is-text-primary title is-size-3-mobile is-size-2"><%= foodtruck.name %></p>
        <% else %>
          <p class="foodtruck-name title is-size-5-mobile is-size-4">Le nom du foodtruck n'est pas encore renseigné.</p>
        <% end %>
        
        <% if foodtruck.description !=nil && foodtruck.description != "" %>
          <p class="speciality is-size-6-mobile is-size-6"><%= foodtruck.description %></p>
        <% else %>  
          <p class="foodtruck-name title is-size-5-mobile is-size-4">La description du foodtruck n'est pas encore renseignée.</p>
        <% end %>
            
        <% if foodtruck.location_id !=nil %>
          <p class="speciality is-size-6-mobile is-size-6 my-2"><b class="is-text-info"> Localisation du jour : </b> <%= Location.find(foodtruck.location_id).adress %>, <%= Location.find(foodtruck.location_id).name %></p>
        <% else %>
          <p class="foodtruck-name title is-size-5-mobile is-size-4">La localisation du foodtruck n'est pas encore renseignée.</p>
        <% end %>
      </div>


        <!-- ********************** Vote/like section ********************************** -->
               
      <% if !current_myfoodtruck_foodtruck %>
        <% if customer_signed_in? %>
          <div class="like-section column is-3">
            <div class="box mt-5 has-text-centered">
              <div class="price">
                <p class="title is-size-5">Je vote pour mon foodtruck préféré</p>
              </div>
              <div class="subtile py-5 is-size-6">
                <% if !current_customer_has_location? %>
                  <p>Vous devez renseigner une localisation pour pouvoir voter</p>
                <% elsif current_customer_has_location? && !voted_once? %>
                  <%= link_to foodtruck_votes_path(@foodtruck.id), method: :post, class:"button is-rounded is-primary" do %>
                    <span class="icon is-small"><%= image_tag("like.png")%></span>
                    <p>Viens chez moi</p>
                  <% end %>
                <% elsif current_customer_has_location? && !last_vote_over_24? %>
                  <p>Veuillez attendre 24 heures pour voter à nouveau</p>
                <% elsif current_customer_has_location? && last_vote_over_24? %>
                  <%= link_to foodtruck_votes_path(@foodtruck.id), method: :post, class:"button is-rounded is-primary" do %>
                    <span class="icon is-small"><%= image_tag("like.png")%></span>
                    <p>Viens chez moi</p>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>

      <% else %>
        <div class="column is-3 is-flex is-justify-content-center">
          <div class="is-flex is-align-items-center">
            <% if foodtruck.logo.attached? %>
              <%= image_tag foodtruck.logo, alt: "Thumbnail [100%x225]", class:"image is-96x96" %>
            <% else %>
              <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQu2DMlO0wSOdL36IyORHd0n1FAKfw0_S4jg&usqp=CAU" alt="Placeholder image" class="image is-96x96 cards-logo-dimension">
            <% end %>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/foodtrucks/_index_header.html.erb
<section class="foodtruck-index-header">
  <div class="jumbotron-body  px-4 is-flex is-flex-direction-column is-align-items-center">
    <div class="has-text-centered">
      <p class="title is-size-4-mobile is-size-2 is-text-white mt-5" >Les foodtrucks disponibles en ce moment à Paris</p>
    </div>
  </div>
</section>

app/views/foodtrucks/_location.html.erb
<div class="section">
  <div class=" container is-flex is-flex-direction-column is-align-items-center item-list"> 
    <% if foodtruck.location_id != nil %>
      <p class="title has-text-centered is-size-3-mobile is-size-4 py-5">
        Aujourd'hui <%= foodtruck.name %> est à cette adresse : <%= Location.find(foodtruck.location_id).adress %>, <%= Location.find(foodtruck.location_id).name %>
      </p>
      <div class="container-iframe">
        <iframe src=" <%= Location.find(foodtruck.location_id).url_map %> " class="responsive-iframe no-borders" allowfullscreen="" loading="lazy"></iframe>
      </div>     
    <% end %>                               
  </div>
</div>

app/views/foodtrucks/_menu.html.erb
<div class="section">
  <div class=" container box is-flex is-flex-direction-column is-align-items-center item-list"> 
    <p class="title has-text-centered is-size-3-mobile py-5">Le menu chez <%= foodtruck.name %></p>
    <% foodtruck.items.each do |item| %>
      <div class="box p-5 column is-7 is-10-mobile is-flex is-align-items-center is-justify-content-space-between index-items pink-shadow">
        <div class="box-content index-items-content">             
          <p class="title is-5 mb-2 is-text-primary"><%= item.name %></p>
          <p class="subtitle is-5 mt-2"><%= sprintf "%.2f", item.price %>€</p>
          <p class="description mb-5"><%= item.description.truncate(20) %></p>
          <div class="is-flex my-2 is-flex-wrap-wrap is-align-items-center">                         
            <%if !current_myfoodtruck_foodtruck %>
              <%= link_to foodtruck_item_path(foodtruck.id, item.id), class: "button show-button is-rounded is-primary mr-2" do %>
                <span>Voir plus</span>
              <% end %>
              <%= link_to cart_cart_contents_path(item: item.id, quantity: '1'), class: "button is-rounded is-primary mr-2", method:'post', remote: true do %>
                <span class="icon is-small"><%= image_tag("bag.png") %></span>
              <% end %>
            <%end%>
          </div>
        </div>
        <div class="box-content index-items-content">
          <% if item.picture.attached? %>
            <%= image_tag item.picture, alt: "Thumbnail [100%x225]", class: "menu-item-img" %>
          <% else %>
            <img src="https://images.pexels.com/photos/566566/pexels-photo-566566.jpeg?cs=srgb&dl=pexels-foodie-factor-566566.jpg&fm=jpg" alt="food-img" class="menu-item-img">
          <% end %>
        </div>                        
      </div>
    <%end%>                                             
  </div>
</div>

app/views/foodtrucks/index.html.erb
<%= render partial: 'index_header', locals: {foodtrucks: @foodtrucks} %>
<%= render partial: 'cardindex', locals: {foodtrucks: @foodtrucks} %>

app/views/foodtrucks/show.html.erb
<%= render partial: 'firstsection', locals: {foodtruck: @foodtruck} %>
<%= render partial: 'menu', locals: {foodtruck: @foodtruck} %>
<%= render partial: 'location', locals: {foodtruck: @foodtruck} %>