config/routes.rb
Rails.application.routes.draw do
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#homepage"
  get 'team', to: 'static_pages#team'
  get 'contact', to:'static_pages#contact'
  get 'cgv', to:'static_pages#cgv'
  get 'faq', to:'static_pages#faq'
  get 'jobs', to:'static_pages#jobs'

  devise_for :customers

  resource :cart, only: [:show, :create, :destroy] do
    resources :cart_contents, only: [:show, :new, :create, :destroy]
  end


  resource :customer do
    resources :orders
  end
  resources :foodtrucks do
    resources :votes, only: [:show, :create]
    resources :items do
    end
  end

  namespace :myfoodtruck do
    root 'dashboards#show'
    devise_for :foodtrucks
    resource :dashboard, only: [:show]
    resource :foodtruck, only: [:show, :edit, :update, :destroy] do
      resources :items
      resources :orders, only: [:index, :show, :update, :edit]
    end
  end

end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :customer, optional: true
  has_many :cart_contents
  has_many :items, through: :cart_contents


  def total_price
    unless self.items.first.nil?
      self.cart_contents.map {|cart_content| cart_content.item.price*cart_content.item_quantity}.reduce(:+)
    else
      return 0            
    end
  end
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def destroy
    current_shopping_cart.cart_contents.each do | content |
      content.destroy
    end
    redirect_to cart_path
  end
  
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div class="section">
  <div class="columns shopping-cart">
    <div class="column box cart-box is-8 is-flex is-flex-direction-column is-align-items-center mx-5 box-cart-min-height">
      <p class="title is-text-primary is-size-4-mobile">Mon Panier</p>
      <% if current_shopping_cart.cart_contents.count == 0 %>
        <p class="is-text-info mt-4 is-size-5">Votre panier est vide.</p>
      <% else %>
        <% current_shopping_cart.cart_contents.sort.each do |content| %>
          <div class="cart-item box column is-8 is-flex is-align-items-center is-justify-content-space-between is-flex-wrap-wrap mb-5", id="<%= content.created_at %>">
            <div class="box-body my-2 is-flex is-flex-wrap-wrap is-align-items-center">
              <figure class="box-img mb-2 cart-item image mr-5">
                <% if content.item.picture.attached? %>
                  <%= image_tag content.item.picture, alt: "Thumbnail [100%x225]" %>
                <%else%>
                  <img src="https://images.pexels.com/photos/566566/pexels-photo-566566.jpeg?cs=srgb&dl=pexels-foodie-factor-566566.jpg&fm=jpg" alt="food-img" class="menu-item-img">
                <%end%>
              </figure>
              <div class="box-content mr-5">             
                <p class="item-title is-text-primary title is-size-5"><%= content.item.name %></p>
                <div class="is-flex my-1 is-align-items-center">
                  <div class="quantity mr-5">
                    <p class="item-price is-6 subtitle"><%=content.item.description.truncate(12)%></p>
                  </div>                      
                </div>
              </div>
            </div>
            <div class="is-flex my-2 is-flex-wrap-wrap is-align-items-center">                         
              <div class="quantity-x-item-price is-size-4 mr-5 is-flex is-align-items-center">
                <p class="is-size-5 has-text-weight-bold"><%= sprintf "%.2f", content.item.price %>€</p>
                <p class="ml-4 is-size-5">x<%= content.item_quantity %></p>
              </div>
              <%= link_to cart_cart_content_path(content.id), class: "button is-rounded is-danger mr-2", method: :delete, remote: true do %>
                <span class="icon is-small"><i class="fas fa-trash"></i></span>
              <% end %>
            </div>
          </div> 
        <% end %> 
      <% end %>                          
    </div>
    <div class="column is-flex is-flex-direction-column checkout-infos box mx-5 box-cart-min-height">
      <div class="my-4">
        <% if current_shopping_cart.items.count > 1 %>
          <p class="mb-2 is-size-5" id="cart-nb-article"><%= current_shopping_cart.items.count %> articles</p>
        <% else %>
          <p class="mb-2 is-size-5" id="cart-nb-article"><%= current_shopping_cart.items.count %> article</p>
        <% end %>
          <p class="is-size-5">Total TTC : <strong id="cart-total-price"><%= sprintf('%.2f',  current_shopping_cart.total_price) %>€</strong></p>
      </div>
      <% if customer_signed_in? && current_shopping_cart.total_price > 0 %>
        <%= render partial: 'carts/stripe', locals: {current_shopping_cart: current_shopping_cart, total_price: current_shopping_cart.total_price }%>
      <% elsif current_shopping_cart.total_price > 0%>
        <div class="my-2">
          <button class="button is-small-tablet is-rounded is-primary is-largest-btn">
            <span id="guest-payment">Procéder au paiement</span>
          </button>
        </div>
      <% end %>
      <div class="my-2">
        <%= link_to 'Continuer mon shopping', foodtrucks_path, class: "button is-small-tablet is-rounded is-info is-largest-btn" %> 
      </div>  
      
      <% if current_shopping_cart.items.count > 0 %>
        <div class="my-1">
          <%= link_to cart_path, data: { confirm: "Etes vous sur ?" }, method: :delete, class: "button is-small-tablet is-rounded is-danger is-largest-btn" do %>
            <span>Vider le panier</span>
          <% end %>
        </div>
      <% end %>

    </div>              
  </div>
</div>

app/views/carts/_stripe.html.erb
<%= form_tag customer_orders_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
  </article>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-label="Procéder au paiement"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Paiement de votre commande"
          data-amount="<%= current_shopping_cart.total_price*100 %>"
          data-email=<%= current_customer.email %>
          data-locale="auto"
          data-currency="eur">
  </script>
<% end %>

app/views/carts/show.html.erb
<%= render partial: 'cart', locals: {cart_content: @cart_contents} %>
<%= javascript_include_tag 'cart_show', media: 'all' %>