config/routes.rb
Rails.application.routes.draw do
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#homepage"
  get 'team', to: 'static_pages#team'
  get 'contact', to:'static_pages#contact'
  get 'cgv', to:'static_pages#cgv'
  get 'faq', to:'static_pages#faq'
  get 'jobs', to:'static_pages#jobs'

  devise_for :customers

  resource :cart, only: [:show, :create, :destroy] do
    resources :cart_contents, only: [:show, :new, :create, :destroy]
  end


  resource :customer do
    resources :orders
  end
  resources :foodtrucks do
    resources :votes, only: [:show, :create]
    resources :items do
    end
  end

  namespace :myfoodtruck do
    root 'dashboards#show'
    devise_for :foodtrucks
    resource :dashboard, only: [:show]
    resource :foodtruck, only: [:show, :edit, :update, :destroy] do
      resources :items
      resources :orders, only: [:index, :show, :update, :edit]
    end
  end

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :foodtruck
  has_many :order_contents
  has_many :orders, through: :order_contents
  has_many :cart_contents
  has_many :carts, through: :cart_contents
  has_one_attached :picture

  validates :name, presence: true, length: { in: 3..120 }
  validates :description, presence: true, length: { in: 3..1000 }
  validates :price, presence: true, numericality: { greater_than: 0 }

end

app/controllers/feedtruck/items_controller.rb
class Feedtruck::ItemsController < ApplicationController
  before_action :set_foodtruck_item, only: %i[ show edit update destroy ]

  # GET /foodtruck/items or /foodtruck/items.json
  def index
    @foodtruck_items = Foodtruck::Item.all
  end

  # GET /foodtruck/items/1 or /foodtruck/items/1.json
  def show
  end

  # GET /foodtruck/items/new
  def new
    @foodtruck_item = Foodtruck::Item.new
  end

  # GET /foodtruck/items/1/edit
  def edit
  end

  # POST /foodtruck/items or /foodtruck/items.json
  def create
    @foodtruck_item = Foodtruck::Item.new(foodtruck_item_params)

    respond_to do |format|
      if @foodtruck_item.save
        format.html { redirect_to @foodtruck_item, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @foodtruck_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @foodtruck_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foodtruck/items/1 or /foodtruck/items/1.json
  def update
    respond_to do |format|
      if @foodtruck_item.update(foodtruck_item_params)
        format.html { redirect_to @foodtruck_item, notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @foodtruck_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @foodtruck_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foodtruck/items/1 or /foodtruck/items/1.json
  def destroy
    @foodtruck_item.destroy
    respond_to do |format|
      format.html { redirect_to foodtruck_items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foodtruck_item
      @foodtruck_item = Foodtruck::Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def foodtruck_item_params
      params.fetch(:foodtruck_item, {})
    end
end

app/controllers/foodtruck/items_controller.rb
class Foodtruck::ItemsController < ApplicationController
  before_action :set_foodtruck_item, only: %i[ show edit update destroy ]

  # GET /foodtruck/items or /foodtruck/items.json
  def index
    @foodtruck_items = Foodtruck::Item.all
  end

  # GET /foodtruck/items/1 or /foodtruck/items/1.json
  def show
  end

  # GET /foodtruck/items/new
  def new
    @foodtruck_item = Foodtruck::Item.new
  end

  # GET /foodtruck/items/1/edit
  def edit
  end

  # POST /foodtruck/items or /foodtruck/items.json
  def create
    @foodtruck_item = Foodtruck::Item.new(foodtruck_item_params)

    respond_to do |format|
      if @foodtruck_item.save
        format.html { redirect_to @foodtruck_item, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @foodtruck_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @foodtruck_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foodtruck/items/1 or /foodtruck/items/1.json
  def update
    respond_to do |format|
      if @foodtruck_item.update(foodtruck_item_params)
        format.html { redirect_to @foodtruck_item, notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @foodtruck_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @foodtruck_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foodtruck/items/1 or /foodtruck/items/1.json
  def destroy
    @foodtruck_item.destroy
    respond_to do |format|
      format.html { redirect_to foodtruck_items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foodtruck_item
      @foodtruck_item = Foodtruck::Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def foodtruck_item_params
      params.fetch(:foodtruck_item, {})
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]
  before_action :set_foodtruck, only: %i[ show edit update destroy index new]
  before_action :authenticate_foodtruck_owner, only: %i[ update ]

  # GET /items
  def index
    @items = Item.all.where(foodtruck_id: @foodtruck.id)
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # POST /items
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, flash: { success: "Plat créé"} }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to myfoodtruck_foodtruck_path, flash: { success: "Plat mis à jour"} }
      else
        format.html { redirect_back(fallback_location: edit_myfoodtruck_foodtruck_item_path(@item.id), flash: { alert: "Le séparateur entre les euros et les centimes doit être exprimé sous forme de point (exemple: '11.50')" }) }
      end
    end
  end

  # DELETE /items/1
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, flash: { success: "Plat détruit"} }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    def set_foodtruck
      @foodtruck = Foodtruck.find(params[:foodtruck_id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :description, :price, :picture, :foodtruck_id, :id)
    end

    def authenticate_foodtruck_owner
      @item = Item.find(params[:id])
      @item_owner = @item.foodtruck.id
      unless @item_owner == current_myfoodtruck_foodtruck.id
        flash[:alert] = "Désolé, mais vous ne pouvez pas modifier un plat qui n'est pas le vôtre !"
        redirect_to myfoodtruck_foodtruck_path
      end
    end

end

app/controllers/myfoodtruck/items_controller.rb
class Myfoodtruck::ItemsController < ApplicationController
  before_action :set_foodtruck_item, only: %i[ show edit update destroy ]

  # GET /foodtruck/items or /foodtruck/items.json
  def index
    @foodtruck_items = Item.all
  end

  # GET /foodtruck/items/new
  def new
    @foodtruck_item = Item.new.picture.attach(:picture)
  end

  # GET /foodtruck/items/1/edit
  def edit
    @myfoodtruck = current_myfoodtruck_foodtruck
    @item = Item.find(params[:id])
  end

  # POST /foodtruck/items or /foodtruck/items.json
  def create
    @foodtruck_item = Item.new(foodtruck_item_params)

    respond_to do |format|
      if @foodtruck_item.save
        format.html { redirect_to myfoodtruck_foodtruck_path, notice: "Votre plat a bien été créé." }
        format.json { render :show, status: :created, location: @foodtruck_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @foodtruck_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foodtruck/items/1 or /foodtruck/items/1.json
  def update
    respond_to do |format|
      if @foodtruck_item.update(foodtruck_item_params)
        format.html { redirect_to @myfoodtruck, notice: "Votre plat a bien été mis à jour." }
        format.json { render :show, status: :ok, location: @foodtruck_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @foodtruck_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foodtruck/items/1 or /foodtruck/items/1.json
  def destroy
    @foodtruck_item = Item.find(params[:id])
    @foodtruck_item.destroy
    respond_to do |format|
      format.html { redirect_to myfoodtruck_foodtruck_path, notice: "Votre plat a bien été supprimé" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foodtruck_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def foodtruck_item_params
      params.permit(:id, :name, :description, :price, :picture).merge(foodtruck_id: current_myfoodtruck_foodtruck.id)
    end
    
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/myfoodtruck/items_helper.rb
module Myfoodtruck::ItemsHelper
end

app/views/items/_checkout-section.html.erb
<div class="section pb-2">
  <div class="columns is-variable is-0 is-centered is-vcentered is-multiline checkout-section">
    <div class="column has-text-centered is-6">
      <%= image_tag(item.picture, alt:"image", class:"checkout-section-image")%>
    </div>
    <div class="column is-4">
      <p class="title"><%=item.name%></p>
      <p class="subtitle"><%=item.description%></p>
      <p class="price is-size-4"><%= sprintf('%.2f', item.price) %>€</p>
      <div class="quantity is-flex is-align-items-center mt-4">
        <%= form_with  url: cart_cart_contents_path(item: item.id) do |f| %>
          <div class="is-flex is-align-items-center">
            <span class= "button quantity-button", id="minus-btn"><i class="fas fa-minus"></i></span>
              <%= f.number_field 'quantity', min: 1, step: 1, class:"mx-2 button is-outlined quantity-counter", value: '1' %>
            <span class= "button quantity-button", id="plus-btn"><i class="fas fa-plus"></i></span>
          </div>
          <div class="actions mt-4">
            <%= f.submit "Ajouter au panier", class: "button is-rounded is-normalest-btn is-primary" %>
          </div>
          <div class="actions mt-4">
            <%= link_to "Retour", :back, class: "button is-secondary is-rounded is-normalest-btn" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/items/_others_food.html.erb
<div class="section">
  <div class="container">
    <div class="title mb-5">
      Les autres plats de ce chef
    </div>
    <% if item.foodtruck.items.count > 3 %>
      <div class="columns is-centered grid-list-display">
        <% item.foodtruck.items.sample(3).each do |food| %>
          <div class="card column other-food-card">
            <%= link_to foodtruck_item_path(food.foodtruck.id, food.id) do %>
              <div class="card-image">
                <figure class="image is-4by3">
                  <%= image_tag(food.picture, alt: "food-img", class: "item-other-image") %>
                </figure>
              </div>       
              <div class="card-content">                    
                <p class="title is-size-4"><%= food.name %></p>
                <p class="subtitle is-size-6"><%= sprintf('%.2f', food.price) %>€</p>
                  <%= link_to cart_cart_contents_path(item: food.id, quantity: '1'), class: "button mt-5 is-primary is-rounded", method:'post', remote: true do %>
                    <span class="icon is-small"><%= image_tag("bag.png") %></span>
                    <span>Ajouter au panier</span>
                  <% end %>
              </div> 
            <%end%>             
          </div>
        <%end%>
      <%end%>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<h1>Items de <%= link_to "#{@foodtruck.name}", foodtruck_path(@foodtruck.id) %> </h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= link_to 'Show', foodtruck_item_path(item.foodtruck.id, item.id) %></td> |
        <td><%= link_to 'Edit', edit_foodtruck_item_path(item.foodtruck.id, item.id) %></td> |
        <td><%= link_to 'Ajouter au panier', foodtruck_item_cart_contents_path(item.foodtruck.id, item.id) , method: 'post' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_foodtruck_item_path %>

app/views/items/show.html.erb
<%= render partial: 'checkout-section', locals: {item: @item} %>
<%= render partial: 'others_food', locals: {item: @item} %>
<%= javascript_include_tag 'item_show', media: 'all' %>