config/routes.rb
Rails.application.routes.draw do
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#homepage"
  get 'team', to: 'static_pages#team'
  get 'contact', to:'static_pages#contact'
  get 'cgv', to:'static_pages#cgv'
  get 'faq', to:'static_pages#faq'
  get 'jobs', to:'static_pages#jobs'

  devise_for :customers

  resource :cart, only: [:show, :create, :destroy] do
    resources :cart_contents, only: [:show, :new, :create, :destroy]
  end


  resource :customer do
    resources :orders
  end
  resources :foodtrucks do
    resources :votes, only: [:show, :create]
    resources :items do
    end
  end

  namespace :myfoodtruck do
    root 'dashboards#show'
    devise_for :foodtrucks
    resource :dashboard, only: [:show]
    resource :foodtruck, only: [:show, :edit, :update, :destroy] do
      resources :items
      resources :orders, only: [:index, :show, :update, :edit]
    end
  end

end

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="<%= bulma_class_for_flash(type) %> notification m-0" role="alert">
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer py-4">
  <div class="content">
        
    <div class="columns">
      <%= image_tag("logo.png", style:"max-height: 100px",alt: "logo", class:"is-flex footer-picture")%>
        <div class="column is-flex is-flex-direction-column is-half-mobile is-offset-one-quarter-mobile footer-column">  
          <h4 class="title">Feedtruck SAS</h4>
          <p class="mb-1">8 rue Jeanne d’Asnières</p>
          <p class="mb-1">92110 Clichy</p>
          <p class="mb-1">01 84 20 22 46</p>  
        </div>
        <div class="column  is-flex is-flex-direction-column is-half-mobile is-offset-one-quarter-mobile footer-column">
          <h4 class="title">PLAN DU SITE</h4>
          <%= link_to root_path, class: "is-text-primary" do %>Accueil<% end %>
          <% if current_customer %>
            <%= link_to  customer_path, class: "is-text-primary" do %>Mon compte<% end %>
          <% end %>
          <%= link_to  contact_path, class: "is-text-primary" do %>Nous contacter<% end %>
          <%= link_to  team_path, class: "is-text-primary" do %>Notre équipe<% end %>
        </div>
        <div class="column is-flex is-flex-direction-column is-half-mobile is-offset-one-quarter-mobile footer-column">
          <h4 class="title">RESSOURCES</h4>
          <%= link_to  faq_path, class: "is-text-primary" do %>FAQ<% end %>
          <%= link_to  cgv_path, class: "is-text-primary" do %>CGV<% end %>
          <%= link_to  jobs_path, class: "is-text-primary" do %>Jobs<% end %>
        </div>
        <div class="column is-flex is-flex-direction-column is-half-mobile is-offset-one-quarter-mobile footer-column">
          <h4 class="title">NOS RÉSEAUX SOCIAUX</h4>
          <div class="is-flex is-flex-direction-row">
          <%= link_to "", "https://www.facebook.com/profile.php?id=100070054593311", class: "mr-5 icon-primary-color fab fa-facebook-square fa-3x pr-2", :target => "_blank" %></td>
          <%= link_to "", "https://www.instagram.com/equipe_feedtruck/", class: "mr-5 icon-primary-color fab fa-instagram fa-3x pr-2", :target => "_blank" %></td>
          <%= link_to "", "https://twitter.com/feed_truck", class: "mr-5 icon-primary-color fab fa-twitter-square fa-3x", :target => "_blank" %></td>             
        </div>     
      </div>
    </div>
    
  </div>
</footer>   

app/views/layouts/_navbar.html.erb
<nav class="navbar has-shadow is-white is-fixed-top"   hrole="navigation" aria-label="main navigation">
  <div class="navbar-brand is-flex is-align-items-center">
    <% if myfoodtruck_foodtruck_signed_in? %>
      <%= link_to myfoodtruck_root_path do %>
        <span class="navbar-item">
          <%= image_tag("logo.png", class:"icon-small-size")%>
          <div>
            <p class="is-size-3 title is-text-dark has-text-weight-bold">FeedTruck</p>
          </div>
        </span>
      <%end%>
    <% elsif customer_signed_in? %>
      <%= link_to foodtrucks_path do %>
        <span class="navbar-item">
          <%= image_tag("logo.png", class:"icon-small-size")%>
          <div>
            <p class="is-size-3 title is-text-dark has-text-weight-bold">FeedTruck</p>
          </div>
        </span>
      <% end %>
    <% else %>           
      <%= link_to root_path do %>
        <span class="navbar-item">
          <%= image_tag("logo.png", class:"icon-small-size") %>
          <div>
            <p class="is-size-3 title is-text-dark has-text-weight-bold">FeedTruck</p>
          </div>
        </span>
      <%end%>
    <% end %>         
    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
           
  <div id="main-navbar" class="navbar-menu">
    <div class="navbar-end is-flex is-align-items-center is-justify-content-center ">           
      <% if !myfoodtruck_foodtruck_signed_in? %>
        <div class="navbar-item">
          <%= link_to cart_path do %>
            <div class="cart is-flex">
              <div class="cart-icon">
                <%= image_tag("bag-dark.png", alt:"cart-icon") %>
              </div>
              <div class="cart-items-count nav-cart-button">
                <p class="has-text-centered is-text-white" id="cart-count"><%= current_shopping_cart.cart_contents.count %></p>
              </div>
            </div>
          <% end %>
        </div> 
      <% end %>
      <%if !customer_signed_in? && !myfoodtruck_foodtruck_signed_in? %>           
        <div class="navbar-item">
          <div class="dropdown drop_but1">
            <div class="dropdown-trigger">
              <button class="button is-primary is-rounded mr-2" aria-haspopup="true" aria-controls="dropdown-menu">
                <span>S'inscrire</span>
                <span class="icon is-small"><i class="fas fa-angle-down" aria-hidden="true"></i></span>
              </button>        
            </div>   
            <div class="dropdown-menu" id="dropdown-menu" role="menu">
              <div class="dropdown-content">
                <%= link_to "Gourmet", new_customer_registration_path, class: "dropdown-item" %>
                <%= link_to "Foodtruck", new_myfoodtruck_foodtruck_registration_path, class: "dropdown-item" %>
              </div>
            </div>                     
          </div>
          <div class="dropdown drop_but2">
            <div class="dropdown-trigger">
              <button class="button login-button is-rounded is-light" aria-haspopup="true" aria-controls="dropdown-menu">
                <span>Se connecter</span>
                <span class="icon is-small"><i class="fas fa-angle-down" aria-hidden="true"></i></span>
              </button>        
            </div>   
            <div class="dropdown-menu" id="dropdown-menu" role="menu">
              <div class="dropdown-content is-rounded">
                <%= link_to "Gourmet", new_customer_session_path, class: "dropdown-item" %>
                <%= link_to "Foodtruck", new_myfoodtruck_foodtruck_session_path, class: "dropdown-item" %>
              </div>
            </div>                     
          </div>
        </div>
      <% elsif customer_signed_in? && !myfoodtruck_foodtruck_signed_in? %>
        <div class="navbar-item">
          <div class="dropdown customer-profile is-hoverable is-right  ">
            <div class="dropdown-trigger">
              <div class="profile-button" aria-haspopup="true" aria-controls="dropdown-menu">
                <i class="fas fa-user-circle fa-2x"></i>               
                <span class="icon is-small"><i class="fas fa-angle-down" aria-hidden="true"></i></span>
              </div>
            </div>
            <div class="dropdown-menu" id="dropdown-menu" role="menu">
              <div class="dropdown-content">
                <%= link_to  customer_path, class: "dropdown-item" do %>Mes infos<% end %>
                <%= link_to  customer_orders_path, class: "dropdown-item" do %>Mes commandes passées<% end %>
                <hr class="dropdown-divider">
                <%= link_to destroy_customer_session_path, class: "dropdown-item", method: :delete do %>
                  <i class="fas fa-power-off"></i>
                  Déconnexion
                <% end %>
              </div>
            </div>
          </div>        
        </div>
      <% elsif !customer_signed_in? && myfoodtruck_foodtruck_signed_in? %> 
        <div class="navbar-item">
          <div class="dropdown customer-profile is-hoverable is-right  ">
            <div class="dropdown-trigger">
              <div class="profile-button" aria-haspopup="true" aria-controls="dropdown-menu">
                <i class="fas fa-user-circle fa-2x"></i>               
                <span class="icon is-small"><i class="fas fa-angle-down" aria-hidden="true"></i></span>
              </div>
            </div>
            <div class="dropdown-menu" id="dropdown-menu" role="menu">
              <div class="dropdown-content">
                <%= link_to  myfoodtruck_foodtruck_path, class: "dropdown-item" do %>Mes infos<% end %>
                <%= link_to  myfoodtruck_dashboard_path, class: "dropdown-item" do %>Mon dashboard<%end%>
                <hr class="dropdown-divider">
                <%= link_to destroy_myfoodtruck_foodtruck_session_path, class: "dropdown-item", method: :delete do %>
                  <i class="fas fa-power-off"></i>
                  Déconnexion
                <% end %>
              </div>
            </div>
          </div>        
        </div>
      <% else %>         
        <%= button_to destroy_myfoodtruck_foodtruck_session_path, class: "button login-button is-rounded is-light", method: :delete do %>
          <i class="fas fa-power-off"></i>
          Déco_Foodtruck
        <% end %>               
        <%= button_to destroy_customer_session_path, class: "button login-button is-rounded is-light", method: :delete do %>
          <i class="fas fa-power-off"></i>
          Déco_Customer
        <% end %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Feedtruck</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link rel="icon" type="image/png" sizes="32x32" href="icon-browser.png">
    <link rel="icon" type="image/png" sizes="16x16" href="icon-browser.png">
    <script src="https://kit.fontawesome.com/eb8c289520.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <%= render 'layouts/navbar'%>
      <%=render "layouts/flash" %>
          <%= yield %>
      <%= render 'layouts/footer'%>
      <%= javascript_include_tag 'application', media: 'all' %>  
  </body>
</html>